"""Core pydantic data models shared across all layers.

This package is a leaf dependency: it must not import from ``cli``, ``daemon``,
or ``adapter``.
"""

from mavctl.models.commands import MAV_RESULT_NAMES, CommandOutcome, WaitStatus
from mavctl.models.link import (
    DEFAULT_GCS_SOURCE_COMPONENT,
    DEFAULT_GCS_SOURCE_SYSTEM,
    validate_source_system,
)
from mavctl.models.mission import (
    ARDUPILOT_HOME_SLOT_SEQ,
    MISSION_COMMAND_LAND,
    MISSION_COMMAND_RETURN_TO_LAUNCH,
    MISSION_COMMAND_TAKEOFF,
    MISSION_COMMAND_WAYPOINT,
    MISSION_FRAME_GLOBAL,
    MISSION_FRAME_GLOBAL_RELATIVE_ALT,
    MISSION_FRAME_GLOBAL_RELATIVE_ALT_INT,
    MISSION_MAX_ITEMS,
    MISSION_RESULT_NAMES,
    MISSION_TYPE_MISSION,
    DownloadedMissionV1,
    MissionItem,
    MissionItemIntFields,
    MissionLand,
    MissionOutcome,
    MissionRtl,
    MissionTakeoff,
    MissionV1,
    MissionWaypoint,
    UnsupportedRemoteMissionItem,
    home_slot_int_fields,
    is_home_slot_item,
    mission_item_from_remote,
    mission_item_to_int_fields,
    mission_result_name,
)
from mavctl.models.operation import (
    TERMINAL_OPERATION_STATES,
    OperationKind,
    OperationSnapshot,
    OperationState,
)
from mavctl.models.protocol import (
    DaemonResponse,
    ExitCode,
    RpcError,
    RpcRequest,
)
from mavctl.models.state import (
    Battery,
    GpsInfo,
    HomePosition,
    MissionExecutionState,
    VehicleState,
)
from mavctl.models.telemetry import Attitude, Position, Telemetry, Velocity

__all__ = [
    "ARDUPILOT_HOME_SLOT_SEQ",
    "DEFAULT_GCS_SOURCE_COMPONENT",
    "DEFAULT_GCS_SOURCE_SYSTEM",
    "MAV_RESULT_NAMES",
    "MISSION_COMMAND_LAND",
    "MISSION_COMMAND_RETURN_TO_LAUNCH",
    "MISSION_COMMAND_TAKEOFF",
    "MISSION_COMMAND_WAYPOINT",
    "MISSION_FRAME_GLOBAL",
    "MISSION_FRAME_GLOBAL_RELATIVE_ALT",
    "MISSION_FRAME_GLOBAL_RELATIVE_ALT_INT",
    "MISSION_MAX_ITEMS",
    "MISSION_RESULT_NAMES",
    "MISSION_TYPE_MISSION",
    "TERMINAL_OPERATION_STATES",
    "Attitude",
    "Battery",
    "CommandOutcome",
    "DaemonResponse",
    "DownloadedMissionV1",
    "ExitCode",
    "GpsInfo",
    "HomePosition",
    "MissionExecutionState",
    "MissionItem",
    "MissionItemIntFields",
    "MissionLand",
    "MissionOutcome",
    "MissionRtl",
    "MissionTakeoff",
    "MissionV1",
    "MissionWaypoint",
    "OperationKind",
    "OperationSnapshot",
    "OperationState",
    "Position",
    "RpcError",
    "RpcRequest",
    "Telemetry",
    "UnsupportedRemoteMissionItem",
    "VehicleState",
    "Velocity",
    "WaitStatus",
    "home_slot_int_fields",
    "is_home_slot_item",
    "mission_item_from_remote",
    "mission_item_to_int_fields",
    "mission_result_name",
    "validate_source_system",
]
